function ResearchPreview() {
  try {
    const featuredResearch = [
      {
        id: 1,
        title: "Frames in Krein spaces arising from a non-regular W-metric",
        journal: "Banach Journal of Mathematical Analysis",
        year: "2015",
        visita : "https://scholar.google.com/scholar?cites=8851253150789622794&as_sdt=2005&sciodt=0,5&hl=es",
        category: "Frames y Wavelets"
      },
      {
        id: 2,
        title: "C*-algebra generated by horizontal Toeplitz operators on the Fock space",
        journal: "Boletín de la Sociedad Matemática Mexicana",
        year: "2016",
        visita : "https://scholar.google.com/scholar?hl=es&as_sdt=2005&cites=3886994937327349897&scipsc=1&q=&btnG=",
        category: "Teoría de operadores de Toeplitz"
      },
      {
        id: 3,
        title: "Radial Toeplitz operators on the Fock space and square-root-slowly oscillating sequences",
        journal: "Complex Analysis and Operator Theory",
        year: "2016",
        visita : "https://scholar.google.com/scholar?hl=es&as_sdt=2005&cites=4729150020449842084&scipsc=1&q=&btnG=",
        category: "Teoría de operadores de Toeplitz"
      }
    ];

    return (
      <section className="py-20 bg-white" data-name="research-preview" data-file="components/ResearchPreview.js">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-[var(--primary-color)] mb-4">Investigaciones Destacadas</h2>
            <div className="w-20 h-1 bg-[var(--accent-color)] mx-auto mb-4"></div>
            <p className="text-lg text-[var(--text-secondary)] max-w-2xl mx-auto">
              Publicaciones más citadas en revistas científicas de alto impacto
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8 mb-8">
            {featuredResearch.map(research => (
              <div key={research.id} className="card">
                <div className="mb-4">
                  <span className="inline-block px-3 py-1 bg-[var(--secondary-color)] bg-opacity-10 text-white rounded-full text-sm font-semibold">
                    {research.category}
                  </span>
                </div>
                <h3 className="text-xl font-bold mb-3 text-[var(--primary-color)]">{research.title}</h3>
                <p className="text-[var(--text-secondary)] mb-2">{research.journal}</p>
                <div className="flex items-center gap-4 text-sm text-[var(--text-secondary)]">
                            <span className="flex items-center">
                              <span className="icon-calendar text-base mr-1"></span>
                              {research.year}
                            </span>
                            <a 
                              href={research.visita} 
                              target="_blank" 
                              rel="noopener noreferrer"
                              className="flex items-center text-[var(--secondary-color)] hover:text-[var(--primary-color)] transition-colors"
                            >
                              <span className="icon-external-link text-base mr-1"></span>
                              Google Scholar
                            </a>
                          </div>
              </div>
            ))}
          </div>

          <div className="text-center">
            <a href="research.html" className="btn-primary">
              Ver Todas las Investigaciones
            </a>
          </div>
        </div>
      </section>
    );
  } catch (error) {
    console.error('ResearchPreview component error:', error);
    return null;
  }
}