function ResearchLines() {
  try {
    const researchLines = [
      {
        id: 1,
        title: "Frames, Wavelets y Teoría de operadores en espacios de Krein",
        icon: "grid-3x3",
        articles: [
          {
            id: 1,
            title: "Continuous frames in Krein spaces. Banach",
            journal: "Banach Journal of Mathematical Analysis",
            year: "2022",
            doi: "10.1007/s43037-021-00166-2"            
          },
          {
            id: 2,
            title: "On hyponormal operators in Krein spaces",
            journal: "Archivum Mathematicum",
            year: "2019",
            doi: "10.5817/AM2019-4-249"            
          },
          {
            id: 3,
            title: "Positive definite biequivalent kernels, duality and applications",
            journal: "International Journal of Mathematical Analysis",
            year: "2017",
            doi: "10.12988/ijma.2017.79120"            
          },
          {
            id: 4,
            title: "Construction and coupling of frames in Hilbert spaces with W-metrics",
            journal: "Revista Integración Temas de Matemáticas",
            year: "2016",
            doi: "10.18273/revint.v34n1-2016005"            
          },
          {
            id: 5,
            title: "Dual and similar frames in Krein spaces",
            journal: "International Journal of Mathematical Analysis",
            year: "2015",
            doi: "10.12988/ijma.2016.6469"            
          },
          {
            id: 6,
            title: "Frames of subspaces in Hilbert spaces with W-metrics",
            journal: "Analele Stiintifice ale Universitatii Ovidius Constanta, Seria Matematica",
            year: "2015",
            doi: "10.1515/auom-2015-0021"            
          },
          {
            id: 7,
            title: "Frames in Krein spaces arising from a non-regular W-metric",
            journal: "Banach Journal of Mathematical Analysis",
            year: "2015",
            doi: "10.15352/bjma/09-1-1"            
          }          
        ]
      },
      {
        id: 2,
        title: "Teoría de Operadores de Toeplitz y C*-Álgebras",
        icon: "box",
        articles: [
          {
            id: 1,
            title: "Constructive approximation of convergent sequences by eigenvalue sequences of radial Toeplitz-Fock operators",
            journal: "Por publicar. Este ha sido aceptado en el Boletin de la Sociedad Matemática Mexicana",
            year: "2026",
            doi: "https://arxiv.org/abs/2503.23276"
          },
          {
            id: 2,
            title: "Radial Toeplitz forms on the weighted Bergman space over the unit disk",
            journal: "Journal of Mathematical Sciences",
            year: "2025",
            doi: "10.1007/s10958-025-07728-x"
          },
          {
            id: 3,
            title: "Approximately invertible elements in non-unital normed algebras" ,
            journal: "Journal of Mathematical Analysis and Applications",
            year: "2023",
            doi: "10.1016/j.jmaa.2022.126986"
          },
          {
            id: 4,
            title: "Capítulo de libro: Separately Radial Fock-Carleson Type Measures for Derivatives of Order k" ,
            journal: "In: Bauer W., Duduchava R., Grudsky S., Kaashoek M. (eds) Operator Algebras, Toeplitz Operators and Related Topics. Operator Theory: Advances and Applications, vol 279. Birkhäuser, Cham.",
            year: "2020",
            doi: "10.1007/978-3-030-44651-2_10"
          },
          {
            id: 5,
            title: "L-Invariant Fock--Carleson Type Measures for Derivatives of Order k and the Corresponding Toeplitz Operators" ,
            journal: "Journal of Mathematical Sciences",
            year: "2019",
            doi: "10.1007/s10958-019-04481-w"
          },
          {
            id: 6,
            title: "C*-algebra generated by horizontal Toeplitz operators on the Fock space",
            journal: "Boletín de la Sociedad Matemática Mexicana",
            year: "2016",
            doi: "10.1007/s40590-016-0110-1"
          },
          {
            id: 7,
            title: "Radial Toeplitz operators on the Fock space and square--root--slowly oscillating sequences",
            journal: "Complex Analysis and Operator Theory",
            year: "2016",
            doi: "10.1007/s11785-016-0557-0"
          },
          {
            id: 8,
            title: "C*-algebra generated by angular Toeplitz operators on the weighted Bergman spaces over the upper half--plane",
            journal: "Integral Equations and Operator Theory",
            year: "2015",
            doi: "10.1007/s00020-015-2243-4"
          },
          {
            id: 9,
            title: "C*-algebra of angular Toeplitz operators on Bergman spaces over the upper half--plane",
            journal: "Commununications in Mathematical Analysis",
            year: "2014",
            doi: "http://projecteuclid.org/euclid.cma/1418919761"
          }
        ]
      },
      {
        id: 3,
        title: "Redes Neuronales y Aprendizaje Automático",
        icon: "network",
        articles: [
          {
            id: 1,
            title: "Unsupervised neural networks with random weights for large-scale feature extraction",
            journal: "Neural Networks",
            year: "2026, submitted",
            doi: "10.1016/j.neunet.2024.xxxxx"
          }
        ]
      }
    ];

    return (
      <section className="py-20 bg-white" data-name="research-lines" data-file="components/ResearchLines.js">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-[var(--primary-color)] mb-4">Publicaciones por Líneas de Investigación</h2>
            <div className="w-14 h-1 bg-[var(--accent-color)] mx-auto"></div>
          </div>

          <div className="space-y-12">
            {researchLines.map(line => (
              <div key={line.id} className="card border-t-4 border-[var(--secondary-color)]">
                <div className="flex items-center mb-6">
                  <div className="w-14 h-14 bg-[var(--secondary-color)] rounded-xl flex items-center justify-center mr-4">
                    <span className={`icon-${line.icon} text-2xl text-white`}></span>
                  </div>
                  <h3 className="text-2xl font-bold text-[var(--primary-color)]">{line.title}</h3>
                </div>

                <div className="space-y-4">
                  {line.articles.map(article => (
                    <div key={article.id} className="bg-[var(--surface)] rounded-lg p-4 hover:shadow-md transition-shadow">
                      <div className="flex items-start justify-between">
                        <div className="flex-1">
                          <h4 className="text-lg font-bold text-[var(--primary-color)] mb-2">{article.title}</h4>
                          <p className="text-[var(--text-secondary)] mb-2">{article.journal}</p>
                          <div className="flex items-center gap-4 text-sm text-[var(--text-secondary)]">
                            <span className="flex items-center">
                              <span className="icon-calendar text-base mr-1"></span>
                              {article.year}
                            </span>
                            <a 
                              href={`https://doi.org/${article.doi}`} 
                              target="_blank" 
                              rel="noopener noreferrer"
                              className="flex items-center text-[var(--secondary-color)] hover:text-[var(--primary-color)] transition-colors"
                            >
                              <span className="icon-external-link text-base mr-1"></span>
                              DOI: {article.doi}
                            </a>
                          </div>
                        </div>
                        <div className="w-10 h-10 bg-[var(--accent-color)] bg-opacity-10 rounded-lg flex items-center justify-center flex-shrink-0 ml-4">
                          <span className="icon-file-text text-lg text-white"></span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    );
  } catch (error) {
    console.error('ResearchLines component error:', error);
    return null;
  }
}